model_params:
  activation_name: 'leaky_relu'  # Optional: leaky_relu|tanh|relu|sigmoid

exp_params:
  lr: 0.001
  num_epochs: 100
  batch_size: 50  # 512 for MIMIC, Credit, 50 for Breast
  lmd: 0.9  # the weight of embedding loss
